### PR TITLE
Move to extension-ci-tools, enable distribution of nightly versions

### PR DESCRIPTION
**Pull request by carlopi**
Include https://github.com/duckdb/substrait/pull/108, plus fixes to build system.

Note that while building there are a few warnings connected to targets like:
```
Makefile:20: warning: overriding commands for target `pull'
extension-ci-tools/makefiles/duckdb_extension.Makefile:122: warning: ignoring old commands for target `pull'
Makefile:43: warning: overriding commands for target `test_release'
extension-ci-tools/makefiles/duckdb_extension.Makefile:82: warning: ignoring old commands for target `test_release'
Makefile:46: warning: overriding commands for target `test_debug'
extension-ci-tools/makefiles/duckdb_extension.Makefile:85: warning: ignoring old commands for target `test_debug'
Makefile:63: warning: overriding commands for target `format'
extension-ci-tools/makefiles/duckdb_extension.Makefile:115: warning: ignoring old commands for target `format'
Makefile:69: warning: overriding commands for target `update'
extension-ci-tools/makefiles/duckdb_extension.Makefile:119: warning: ignoring old commands for target `update'
```

Those might need to double checked, relevant code is likely already in extension-ci-tools, but I am not completely sure.

### CODE REVIEW

**Comment by carlopi** [comment]
I think this should sort of work, although it might need some minor touches.

**Comment by pdet** [comment]
Thanks for picking this up!

I think the SQL tests are not running?
`No test cases matched '/Users/runner/work/substrait/substrait/test/*'`

**Comment by carlopi** [comment]
@pdet: nice catch, up to the next

**Comment by pdet** [comment]
LGTM! Thanks Carlo!!

**Comment by pdet** [comment]
@carlopi I just gave this a go and got

```
con.execute("FORCE INSTALL substrait FROM core_nightly")
duckdb.duckdb.HTTPException: HTTP Error: Failed to download extension "substrait" at URL "http://nightly-extensions.duckdb.org/v1.1.0/osx_arm64/substrait.duckdb_extension.gz" (HTTP 403)
Extension "substrait" is an existing extension.
```

**Comment by carlopi** [comment]
Yes, I had seen it earlier, I think https://github.com/duckdb/substrait/pull/110 solves this.

**Comment by carlopi** [comment]
I think it worked:
```sql
FORCE INSTALL substrait from core_nightly;
LOAD substrait;
SELECT extension_name, extension_version, install_mode, installed_from FROM duckdb_extensions() WHERE extension_name = 'substrait';
```
```
┌────────────────┬───────────────────┬──────────────┬────────────────┐
│ extension_name │ extension_version │ install_mode │ installed_from │
│    varchar     │      varchar      │   varchar    │    varchar     │
├────────────────┼───────────────────┼──────────────┼────────────────┤
│ substrait      │ d8ca65b           │ REPOSITORY   │ core_nightly   │
└────────────────┴───────────────────┴──────────────┴────────────────┘
```

**Pull request merged**
